# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: git clone https://github.com/DataWorks-NC/durham-quality-of-life-data.git data
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: npm install
      - run: npm install --only=dev

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build-site
      - run: npx bundlesize

      # Performance test
      - run: sudo npm install -g @lhci/cli@0.5.x
      - run: |
            if [ "$CIRCLECI_BRANCH" = "main" ]; then
              lhci autorun --uploadUrlMap
            else
              lhci autorun
            fi

      # Generate a sitemap based on what's currently on dev site.
      - run: |
          if [ "$CIRCLECI_BRANCH" = "main" ]; then
            npm run build-sitemap-dev
          fi

      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - .circleci/*

  deploy_prod: &DEPLOY_PROD
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/

      # Add robots file for production.
      - run: cp /tmp/workspace/.circleci/robots-prod.txt /tmp/workspace/dist/robots.txt

      # Tweak sitemap URLs
      - run: sed -i 's/nbhdcompassdev\.azurewebsites\.us/compass\.durhamnc\.gov/g' /tmp/workspace/dist/sitemap.xml

      # Push code to Azure blob storage
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "prod"

  deploy_dev:
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace

      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "dev"

  deploy_stage:
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "stage"

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy_stage:
          requires:
            - build
          filters:
            branches:
              only:
                staging
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                develop

      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only:
                main
