# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: git clone https://github.com/DataWorks-NC/durham-quality-of-life-data.git data
      - run: sed -i "s/MAPBOX_ACCESS_TOKEN/$MAPBOX_ACCESS_TOKEN/" .circleci/config.private.js
      - run: sed -i "s/ROLLBAR_ACCESS_TOKEN/$ROLLBAR_ACCESS_TOKEN/" .circleci/config.private.js
      - run: sed -i "s/GOOGLE_ANALYTICS_ID/$GOOGLE_ANALYTICS_ID/" .circleci/config.private.js
      - run: cp ./.circleci/config.private.js data/config/private.js
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-

      - run: npm install
      - run: npm install --only=dev

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build-site
      - run: npx bundlesize
      - run: mkdir /tmp/workspace
      - persist_to_workspace:
          root: .
          paths:
            - dist/*
            - .circleci/*

  deploy_prod: &DEPLOY_PROD
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/

      # Add robots file for production.
      - run: cp /tmp/workspace/.circleci/robots-prod.txt /tmp/workspace/dist/robots.txt
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "prod"

  update_sitemap:
    docker:
      - image: circleci/node:jessie-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: npm install
      - run: npm install --only=dev
      - run: npm run build-sitemap
      - persist_to_workspace:
          root: .
          paths:
            - dist/*

  re_deploy_prod:
    <<: *DEPLOY_PROD

  deploy_dev:
    docker:
      - image: microsoft/azure-cli
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: pip install -r .circleci/requirements.txt
          working_directory: /tmp/workspace/
      - run:
          command: python .circleci/deploy.py /tmp/workspace/dist
          working_directory: /tmp/workspace/
          environment:
            AZURE_DESTINATION_BLOB: "dev"

  performance_test_dev:
    docker:
      - image: circleci/node:jessie-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: npm install
      # Save google auth credentials to the file they're supposed to be in so as to avoid having to manually authorize.
      - run: mkdir /home/circleci/.credentials
      - run: echo $PWMETRICS_GOOGLE_CREDENTIALS > /home/circleci/.credentials/sheets.googleapis.com-nodejs-pwmetrics.json
      - run: npx pwmetrics https://nbhdcompassdev.azurewebsites.us/en/compass/PTLAT/tract --config=./.circleci/pwmetrics-config.js
      - run: npx pwmetrics https://nbhdcompassdev.azurewebsites.us/en/report/blockgroup?selected=370630019001 --config=./.circleci/pwmetrics-config.report.js

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy_dev:
          requires:
            - build
          filters:
            branches:
              only:
                develop
      - performance_test_dev:
          requires:
            - deploy_dev

      - deploy_prod:
          requires:
            - build
          filters:
            branches:
              only:
                master

#      - update_sitemap:
#          requires:
#            - deploy_prod
#          filters:
#            branches:
#              only:
#                master
#
#      - re_deploy_prod: # Re-deploy to prod after sitemap built.
#          requires:
#            - update_sitemap
#          filters:
#            branches:
#              only:
#                master
